### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by srih4ri** [srih4ri/fts#1]
- [ ] Identify images based on their content, rather than url.
- [ ] Store effeciently and make testing of blocked images effecient.
- [ ] Add block links for newly added images.
